export const ActionTypes = {
  ADD_ACTION_TO_QUEUE: 'offline/ADD_ACTION_TO_QUEUE',
  REMOVE_ACTION_FROM_QUEUE: 'offline/REMOVE_ACTION_FROM_QUEUE',
  ACTION_EXEC_ERROR: 'offline/ACTION_EXEC_ERROR',
  ACTION_EXEC_SUCCESS: 'offline/ACTION_EXEC_SUCCESS',
  SET_QUEUE_PROCESSING_STATUS: 'offline/SET_QUEUE_PROCESSING_STATUS',
  UNSET_QUEUE_PROCESSING_STATUS: 'offline/UNSET_QUEUE_PROCESSING_STATUS',
  SET_ACTION_PROCESSING_STATUS: 'offline/SET_ACTION_PROCESSING_STATUS',
  RESET_QUEUE: 'offline/RESET_QUEUE',
};
