export const ActionTypes = {
  SHOW_LOADER: 'supervisor/global/SHOW_LOADER',
  HIDE_LOADER: 'supervisor/global/HIDE_LOADER',
  SET_FIREBASE_DEVICE_TOKEN: 'supervisor/global/SET_FIREBASE_DEVICE_TOKEN',
  SUBSCRIBE_TOKEN_TO_TOPIC: 'supervisor/global/SUBSCRIBE_TOKEN_TO_TOPIC',
  TOGGLE_SIDE_DRAWER: 'supervisor/global/TOGGLE_SIDE_DRAWER',
  GET_DEVICE_TOKEN: 'supervisor/global/GET_DEVICE_TOKEN',
  SET_DEVICE_TOKEN: 'supervisor/global/SET_DEVICE_TOKEN',
  SET_AUTH_STATE: 'supervisor/global/SET_AUTH_STATE',
  RESET_AUTH_STATE: 'supervisor/global/RESET_AUTH_STATE',
  GET_SITE_DATA: 'supervisor/global/GET_SITE_DATA',
  LOGOUT_USER: 'supervisor/global/LOGOUT_USER',
  SET_CURRENT_SITE: 'supervisor/global/SET_CURRENT_SITE',
  SEND_TO_EVENT_TRUCK: 'supervisor/global/SEND_TO_EVENT_TRUCK',
  SET_COOKIE_CONSENT_STATUS: 'supervisor/global/SET_COOKIE_CONSENT_STATUS',
  GET_TRIPS_DATA: 'supervisor/global/GET_TRIPS_DATA',
  TRIPS_DATA_SUCCESS: 'supervisor/global/TRIPS_DATA_SUCCESS',
  SET_APP_FILTERS: 'supervisor/global/SET_APP_FILTERS',
  SET_REDIRECT_TO_PLAN: 'supervisor/global/SET_REDIRECT_TO_PLAN',
  SUBMIT_PLAN_TRIPS: 'supervisor/global/SUBMIT_PLAN_TRIPS',
  SUBMIT_TRIP_SUCCESS: 'supervisor/global/SUBMIT_TRIP_SUCCESS',
  CREATE_TRIP: 'supervisor/global/CREATE_TRIP',
  SET_SELECTED_TRIPS: 'supervisor/global/SET_SELECTED_TRIPS',
  GET_CLIENT_LIST: 'supervisor/global/GET_CLIENT_LIST',
  SET_CLIENT_LIST: 'supervisor/global/SET_CLIENT_LIST',
  SET_TRIPS_DATA: 'supervisor/global/SET_TRIPS_DATA',
};
